version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      security-patches:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
